services:
  orderservice:
    build:
     context: .
     dockerfile: OrderServiceApi/Dockerfile
    ports:
      - 9100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PaymentService__BaseUrl=http://paymentservice:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ops.seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    volumes:
      - sqlite_data_orderservice:/app/data
    depends_on:
      - paymentservice
    networks:
      - ops

  paymentservice:
    build:
     context: .
     dockerfile: PaymentServiceApi/Dockerfile
    ports:
      - 5061:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ops.seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    volumes:
      - sqlite_data_paymentservice:/app/data
    networks:
      - ops

  ops.seq:
    image: datalust/seq:latest
    container_name: Ops.Seq
    volumes:
      - ./containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    networks:
      - ops
    ports:
      - 5341:5341
      - 8081:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks:
      - ops

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      # - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    networks:
      - ops

networks:
  ops:
    driver: bridge

volumes:
  sqlite_data_orderservice: {}
  sqlite_data_paymentservice: {}
