global:
  scrape_interval: 15s
  # scrape_timeout: "10s"
  # evaluation_interval: "1m"
  # body_size_limit: "0"
  # sample_limit: 0
  # label_limit: 0
  # label_name_length_limit: 0
  # label_value_length_limit: 0
  # target_limit: 0

scrape_configs:
  - job_name: 'dotnet-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'orderservice:80'
          - 'paymentservice:80'